### ISSUE TITLE
any improvements from v3 proposal

### ISSUE THREAD

**Issue by phanirithvij** [ogarcia/rockpass#4]
https://github.com/lesspass/lesspass/issues/389

I personally would like it if 2fa codes (totp) were saved in the db but I'm no security expert, best to save 2fa codes in something outside like a dedicated 2fa application? I'm pretty confused.

**Comment by ogarcia** [comment]
The proposal discussed in the linked issue analyzes a hypothetical v3 of the LessPass encryption algorithm and talks about some ideas that may or may not work, but, as of today, there is nothing concrete.

As of today, LessPass does not support maintaining (and encrypting) the OTP code of a site, so it is best to use another tool for that purpose.

In my case I recommend using [pass](https://www.passwordstore.org/) with its [pass-otp extension](https://github.com/tadfisher/pass-otp#readme) (it works very well and is very secure). If you are looking for something for Android, [Aegis](https://github.com/beemdevelopment/aegis#readme) is a very good option.

**Comment by phanirithvij** [comment]
I understand. I am using gopass and authpass (flutter app) for now.
They both have totp support but I thought if lesspass supported it, I can migrate from to lesspass (i.e. rockpass) and use only lesspass from now on.

**Comment by ogarcia** [comment]
Your configuration is very similar to mine (I prefer plain `pass` instead of `gopass` but it is essentially the same).

I use LessPass to generate passwords. All those that don't require 2FA I store them only in Rockpass and in `pass` I store what does require 2FA or backup codes. It's a bit more complex but I'm used to it.

**Comment by phanirithvij** [comment]
I thought you could add experimental support for 2fa in rockpass, maybe slightly deviate from lesspass. Lesspass database server is deprecated anyway and you can decide what rockpass does that's why I thought so.

I'm thinking just use lesspass for everything and use keepassxc/authpass for totp. If there is seamless way to keep pass and keepasxc in sync that's best I found pass-import but not sure if I can import from it to keepassxc. I'll have to do more research thanks for the quick response.
